version: '3.4'

networks:
  dev:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDbDriver
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgres/data
    networks:
      - dev
  message-bus:
    container_name: message-bus
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    restart: always
    labels:
        NAME: "rabbitmq"
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  client-service:
    image: trycatchlearn/client-svc:latest
    container_name: client
    restart: always
    build: 
      context: .
      dockerfile: src/services/Client/Client.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONEMT=Development
      - ASPNETCORE_URLS=http://+80
      - BusConnection__HostName=rabbitmq
      - BusConnection__UserName=guest
      - BusConnection__Password=guest
      - BusConnection__PORT=5672
      - BusConnection__RetryCount=4
      - ConnectionStrings__DefaultConnection=Host=localhost;Username=postgres;Password=postgres;Database=SampleDbDriver; PORT=5433
    ports:
      - "5169:80"
    depends_on:
      - postgres
      - message-bus
  order-service:
    image: trycatchlearn/order-svc:latest
    container_name: order
    restart: always
    build: 
      context: .
      dockerfile: src/services/Order/Order.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONEMT=Development
      - ASPNETCORE_URLS=http://+80
      - BusConnection__HostName=rabbitmq
      - BusConnection__UserName=guest
      - BusConnection__Password=guest
      - BusConnection__PORT=5672
      - BusConnection__RetryCount=4
      - ConnectionStrings__DefaultConnection=Host=localhost;Username=postgres;Password=postgres;Database=SampleDbDriver; PORT=5433
    ports:
      - "5207:80"
    depends_on:
      - postgres
      - message-bus

volumes:
  app_data:
